version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  python: circleci/python@0.2.1

jobs:
  sonarcloud-scan:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - sonarcloud/scan

  run-python-script:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./odin/odin.py
          name: Run Script

workflows:
  main:
    jobs:
      - sconarcloud-scan:
          context: SonarCloud
      - run-python-script
