version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  run-python-script:
    executor: python/default
    steps:
      - checkout
          name: Checkout Repo
      - python/install-deps
          name: Install Python Dependencies
      - run:
          command: python ./odin/odin.py
          name: Run Script

workflows:
  main:
    jobs:
      - run-python-script
